sudo: required
language: bash

cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never

matrix:
  include:
    - env: OS='ubuntu:14.04'
    - env: OS='centos:7'

script:
  - wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone-fate-master-1.4.0.tar.gz
  - tar -xzf  standalone-fate-master-1.4.0.tar.gz 
  - cd standalone-fate-master-1.4.0
  - source init.sh init
  - ls -alh
  - cd standalone-fate-master-1.4.0
  - bash ./federatedml/test/run_test.sh
after_success:
  - cd ./federatedml/test && codecov


