sudo: required
language: generic

cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 3.6

script:
  - wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone-fate-master-1.4.0.tar.gz
  - tar -xzvf  standalone-fate-master-1.4.0.tar.gz
  - cd standalone-fate-master-1.4.0
  - source init.sh init
  - cd standalone-fate-master-1.4.0
  - bash ./federatedml/test/run_test.sh
after_success:
  - cd ./federatedml/test && codecov


